### ISSUE TITLE
[ Help ] 캐러셀(슬라이드) 구현

### ISSUE THREAD

**Issue by lydiacho** [GO-SOPT-GROUP5/ohouse-client#4]
## 💜 어떤 기능인가요?
Help 페이지의 꽃.. carousel을 구현합니다. 
## ✅ To Dos
- [ ] 이미지 여러장 준비 
- [ ] carousel library 선택해서 세팅
- [ ] carousel 기능 구현
- [ ] indicator추가

**Comment by iamphj3** [comment]
너가 우리팀의 꽃이다 ... ㅋ 
화이팅 💙
