### ISSUE TITLE
[ List ] Navigation 연결

### ISSUE THREAD

**Issue by lydiacho** [GO-SOPT-GROUP5/ohouse-client#48]
## 💜 어떤 기능인가요?
매물목록에서 체크리스트 내역보기 누르면 현지 뷰로 넘어가게 연결해요

## ✅ To Dos
- [x] `체크리스트 내역보기` 라우팅
- [x] `매물 등록` 라우팅

**Comment by Yeonseo-Jo** [comment]
내거 구현할때 /help에서 '새로운 매물 등록하기' 버튼 누르면-> /checklist로 넘어가게는 해놔서 요거 구현할 때 /list에서 `+`버튼 누르면 /help 페이지로 라우팅 되는것두 같이 해주면 좋을것 같아용 ~!
